.TH NOCTSCRIPT 1 "June 2025" "NoctVM Project" "User Commands"
.SH NAME
noctscript \- NoctScript IDE

.SH SYNOPSIS
.B noctscript
[\fIFILES\fR]

.SH DESCRIPTION
\fBnoctscript\fR is an IDE for NoctVM.

.SH EXAMPLES
.TP
Run NoctScript IDE.
.B
noctscript

.SH SEE ALSO
.BR noctvm (1)

.SH AUTHOR
Written by Awe Morris.

.SH COPYRIGHT
Copyright © 2025 Awe Morris.  
This is free software; see the source for copying conditions.  
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
